"""empty message

Revision ID: 40800b0f8ef9
Revises: 6a6995fa322a
Create Date: 2023-09-11 00:12:19.416610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40800b0f8ef9'
down_revision = '6a6995fa322a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_filename', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_filename')
    # ### end Alembic commands ###
